
package take_number.call_net;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-07-13T09:18:21.632+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class CreateItemForSDByCustSVSoap_CreateItemForSDByCustSVSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "CreateItemForSDByCustSV");

    private CreateItemForSDByCustSVSoap_CreateItemForSDByCustSVSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CreateItemForSDByCustSV.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CreateItemForSDByCustSV ss = new CreateItemForSDByCustSV(wsdlURL, SERVICE_NAME);
        CreateItemForSDByCustSVSoap port = ss.getCreateItemForSDByCustSVSoap();  
        
        {
        System.out.println("Invoking _do...");
        java.lang.String __do_strdt = "";
        java.lang.String __do_orgID = "";
        java.lang.String __do_userID = "";
        java.lang.String __do_userCode = "";
        java.lang.String __do_userName = "";
        java.lang.String __do__return = port._do(__do_strdt, __do_orgID, __do_userID, __do_userCode, __do_userName);
        System.out.println("_do.result=" + __do__return);


        }

        System.exit(0);
    }

}
