
package alterbom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-25T17:19:22.181+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ExceptionBase", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")
public class UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionBaseFaultFaultMessage extends java.lang.Exception {
    
    private alterbom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase;

    public UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionBaseFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionBaseFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionBaseFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionBaseFaultFaultMessage(String message, alterbom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase) {
        super(message);
        this.exceptionBase = exceptionBase;
    }

    public UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionBaseFaultFaultMessage(String message, alterbom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase, Throwable cause) {
        super(message, cause);
        this.exceptionBase = exceptionBase;
    }

    public alterbom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase getFaultInfo() {
        return this.exceptionBase;
    }
}
