
package alterbom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-25T17:19:22.189+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9ISVMFGBOMIImportBOMSvDoServiceLostExceptionFaultFaultMessage extends java.lang.Exception {
    
    private alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException;

    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceLostExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceLostExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceLostExceptionFaultFaultMessage(String message, alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceLostExceptionFaultFaultMessage(String message, alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException, Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
