
package alterbom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-25T17:19:22.194+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ServiceExceptionDetail", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionDetailFaultFaultMessage extends java.lang.Exception {
    
    private alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail;

    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionDetailFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionDetailFaultFaultMessage(String message, alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail) {
        super(message);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionDetailFaultFaultMessage(String message, alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail, Throwable cause) {
        super(message, cause);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail getFaultInfo() {
        return this.serviceExceptionDetail;
    }
}
