package alterbom.org.ufida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-25T17:19:22.200+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.UFIDA.org", name = "UFIDA.U9.ISV.MFG.BOM.IImportBOMSv")
@XmlSeeAlso({alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ObjectFactory.class, alterbom.data.util.ubf.ufsoft.ObjectFactory.class, alterbom.org.datacontract.schemas._2004._07.system.ObjectFactory.class, alterbom.org.datacontract.schemas._2004._07.ufsoft.ObjectFactory.class, alterbom.org.ufida.entitydata.ObjectFactory.class, alterbom.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, alterbom.exceptions.ubf.ufsoft.ObjectFactory.class, alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf_util.ObjectFactory.class, alterbom.org.datacontract.schemas._2004._07.ufsoft_ubf_pl.ObjectFactory.class, alterbom.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface UFIDAU9ISVMFGBOMIImportBOMSv {

    @Action(input = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IImportBOMSv/Do", output = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IImportBOMSv/DoResponse", fault = {@FaultAction(className = UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IImportBOMSv/DoServiceExceptionFault"), @FaultAction(className = UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IImportBOMSv/DoExceptionFault"), @FaultAction(className = UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionBaseFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IImportBOMSv/DoExceptionBaseFault"), @FaultAction(className = UFIDAU9ISVMFGBOMIImportBOMSvDoServiceLostExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IImportBOMSv/DoServiceLostExceptionFault"), @FaultAction(className = UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionDetailFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IImportBOMSv/DoServiceExceptionDetailFault")})
    @RequestWrapper(localName = "Do", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.Do")
    @WebMethod(operationName = "Do", action = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IImportBOMSv/Do")
    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.DoResponse")
    public void _do(
        @WebParam(name = "context", targetNamespace = "http://www.UFIDA.org")
        java.lang.Object context,
        @WebParam(name = "bOMMasterDTOList", targetNamespace = "http://www.UFIDA.org")
        alterbom.org.ufida.entitydata.ArrayOfUFIDAU9ISVMFGBOMBOMMasterDTO4CreateSvData bOMMasterDTOList,
        @WebParam(name = "contextDTO", targetNamespace = "http://www.UFIDA.org")
        alterbom.org.ufida.entitydata.UFIDAU9CBOPubControllerContextDTOData contextDTO,
        @WebParam(name = "isThrowEx", targetNamespace = "http://www.UFIDA.org")
        java.lang.Boolean isThrowEx,
        @WebParam(mode = WebParam.Mode.OUT, name = "DoResult", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<alterbom.org.ufida.entitydata.ArrayOfUFIDAU9ISVMFGBOMLogDTO4CreateSvData> doResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "outMessages", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<alterbom.exceptions.ubf.ufsoft.ArrayOfMessageBase> outMessages
    ) throws UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionFaultFaultMessage, UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionFaultFaultMessage, UFIDAU9ISVMFGBOMIImportBOMSvDoExceptionBaseFaultFaultMessage, UFIDAU9ISVMFGBOMIImportBOMSvDoServiceLostExceptionFaultFaultMessage, UFIDAU9ISVMFGBOMIImportBOMSvDoServiceExceptionDetailFaultFaultMessage;
}
