
package queryitemrev2.org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-09-25T08:20:45.135+08:00
 * Generated source version: 3.2.0
 * 
 */
public final class QueryBOMVersionByCustSVSoap_QueryBOMVersionByCustSVSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "QueryBOMVersionByCustSV");

    private QueryBOMVersionByCustSVSoap_QueryBOMVersionByCustSVSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QueryBOMVersionByCustSV.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QueryBOMVersionByCustSV ss = new QueryBOMVersionByCustSV(wsdlURL, SERVICE_NAME);
        QueryBOMVersionByCustSVSoap port = ss.getQueryBOMVersionByCustSVSoap();  
        
        {
        System.out.println("Invoking _do...");
        java.lang.String __do_itemCode = "";
        int __do_queryType = 0;
        java.lang.String __do_orgID = "";
        java.lang.String __do_userID = "";
        java.lang.String __do_userCode = "";
        java.lang.String __do_userName = "";
        java.lang.String __do__return = port._do(__do_itemCode, __do_queryType, __do_orgID, __do_userID, __do_userCode, __do_userName);
        System.out.println("_do.result=" + __do__return);


        }

        System.exit(0);
    }

}
