package queryitemrev2.org.tempuri;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.teamcenter.clientx.WSconfig;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-09-25T08:20:45.164+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "QueryBOMVersionByCustSV", 
                  wsdlLocation = "http://192.168.2.70/BarCodeWeb/QueryBOMVersionByCustSV.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class QueryBOMVersionByCustSV extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "QueryBOMVersionByCustSV");
    public final static QName QueryBOMVersionByCustSVSoap12 = new QName("http://tempuri.org/", "QueryBOMVersionByCustSVSoap12");
    public final static QName QueryBOMVersionByCustSVSoap = new QName("http://tempuri.org/", "QueryBOMVersionByCustSVSoap");
    static {
        URL url = null;
        try {
            url = new URL(WSconfig.getUrl() + "BarCodeWeb/QueryBOMVersionByCustSV.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryBOMVersionByCustSV.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.2.70/BarCodeWeb/QueryBOMVersionByCustSV.asmx?wsdl");
        } catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        WSDL_LOCATION = url;
    }

    public QueryBOMVersionByCustSV(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryBOMVersionByCustSV(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryBOMVersionByCustSV() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QueryBOMVersionByCustSV(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryBOMVersionByCustSV(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryBOMVersionByCustSV(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QueryBOMVersionByCustSVSoap
     */
    @WebEndpoint(name = "QueryBOMVersionByCustSVSoap12")
    public QueryBOMVersionByCustSVSoap getQueryBOMVersionByCustSVSoap12() {
        return super.getPort(QueryBOMVersionByCustSVSoap12, QueryBOMVersionByCustSVSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryBOMVersionByCustSVSoap
     */
    @WebEndpoint(name = "QueryBOMVersionByCustSVSoap12")
    public QueryBOMVersionByCustSVSoap getQueryBOMVersionByCustSVSoap12(WebServiceFeature... features) {
        return super.getPort(QueryBOMVersionByCustSVSoap12, QueryBOMVersionByCustSVSoap.class, features);
    }


    /**
     *
     * @return
     *     returns QueryBOMVersionByCustSVSoap
     */
    @WebEndpoint(name = "QueryBOMVersionByCustSVSoap")
    public QueryBOMVersionByCustSVSoap getQueryBOMVersionByCustSVSoap() {
        return super.getPort(QueryBOMVersionByCustSVSoap, QueryBOMVersionByCustSVSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryBOMVersionByCustSVSoap
     */
    @WebEndpoint(name = "QueryBOMVersionByCustSVSoap")
    public QueryBOMVersionByCustSVSoap getQueryBOMVersionByCustSVSoap(WebServiceFeature... features) {
        return super.getPort(QueryBOMVersionByCustSVSoap, QueryBOMVersionByCustSVSoap.class, features);
    }

}
