package querymaterial.org.tempuri;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.teamcenter.clientx.WSconfig;

import querymaterial.org.ufida.UFIDAU9ISVItemIBatchQueryItemByDTOSRV;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-01T18:33:50.407+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "BatchQueryItemByDTOSRVStub", 
                  wsdlLocation = "http://192.168.2.70/U9/Services/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class BatchQueryItemByDTOSRVStub extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "BatchQueryItemByDTOSRVStub");
    public final static QName BasicHttpBindingUFIDAU9ISVItemIBatchQueryItemByDTOSRV = new QName("http://tempuri.org/", "BasicHttpBinding_UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV");
    static {
        URL url = null;
        try {
            url = new URL(WSconfig.getUrl() + "U9/Services/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BatchQueryItemByDTOSRVStub.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.2.70/U9/Services/UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV.svc?wsdl");
        } catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        WSDL_LOCATION = url;
    }

    public BatchQueryItemByDTOSRVStub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BatchQueryItemByDTOSRVStub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BatchQueryItemByDTOSRVStub() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BatchQueryItemByDTOSRVStub(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BatchQueryItemByDTOSRVStub(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BatchQueryItemByDTOSRVStub(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UFIDAU9ISVItemIBatchQueryItemByDTOSRV
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV")
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRV getBasicHttpBindingUFIDAU9ISVItemIBatchQueryItemByDTOSRV() {
        return super.getPort(BasicHttpBindingUFIDAU9ISVItemIBatchQueryItemByDTOSRV, UFIDAU9ISVItemIBatchQueryItemByDTOSRV.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UFIDAU9ISVItemIBatchQueryItemByDTOSRV
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.ISV.Item.IBatchQueryItemByDTOSRV")
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRV getBasicHttpBindingUFIDAU9ISVItemIBatchQueryItemByDTOSRV(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingUFIDAU9ISVItemIBatchQueryItemByDTOSRV, UFIDAU9ISVItemIBatchQueryItemByDTOSRV.class, features);
    }

}
