package querybom.org.ufida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-01T18:34:02.076+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.UFIDA.org", name = "UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv")
@XmlSeeAlso({querybom.org.datacontract.schemas._2004._07.ufsoft_ubf.ObjectFactory.class, querybom.data.util.ubf.ufsoft.ObjectFactory.class, querybom.org.datacontract.schemas._2004._07.system.ObjectFactory.class, querybom.org.datacontract.schemas._2004._07.ufsoft.ObjectFactory.class, querybom.org.ufida.entitydata.ObjectFactory.class, querybom.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, querybom.exceptions.ubf.ufsoft.ObjectFactory.class, querybom.org.datacontract.schemas._2004._07.ufsoft_ubf_util.ObjectFactory.class, querybom.org.datacontract.schemas._2004._07.ufsoft_ubf_pl.ObjectFactory.class, querybom.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface UFIDAU9ISVMFGBOMIQueryBOMSv {

    @Action(input = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv/Do", output = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv/DoResponse", fault = {@FaultAction(className = UFIDAU9ISVMFGBOMIQueryBOMSvDoServiceExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv/DoServiceExceptionFault"), @FaultAction(className = UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv/DoExceptionFault"), @FaultAction(className = UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionBaseFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv/DoExceptionBaseFault"), @FaultAction(className = UFIDAU9ISVMFGBOMIQueryBOMSvDoServiceLostExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv/DoServiceLostExceptionFault"), @FaultAction(className = UFIDAU9ISVMFGBOMIQueryBOMSvDoServiceExceptionDetailFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv/DoServiceExceptionDetailFault")})
    @RequestWrapper(localName = "Do", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.Do")
    @WebMethod(operationName = "Do", action = "http://www.UFIDA.org/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv/Do")
    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.DoResponse")
    public void _do(
        @WebParam(name = "context", targetNamespace = "http://www.UFIDA.org")
        java.lang.Object context,
        @WebParam(name = "qryParams", targetNamespace = "http://www.UFIDA.org")
        querybom.org.ufida.entitydata.ArrayOfUFIDAU9ISVMFGBOMQueryDelParamsDTOData qryParams,
        @WebParam(name = "contextDTO", targetNamespace = "http://www.UFIDA.org")
        querybom.org.ufida.entitydata.UFIDAU9CBOPubControllerContextDTOData contextDTO,
        @WebParam(mode = WebParam.Mode.OUT, name = "DoResult", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<querybom.org.ufida.entitydata.ArrayOfUFIDAU9ISVMFGBOMBOMMasterDTO4CreateSvData> doResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "outMessages", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<querybom.exceptions.ubf.ufsoft.ArrayOfMessageBase> outMessages
    ) throws UFIDAU9ISVMFGBOMIQueryBOMSvDoServiceExceptionFaultFaultMessage, UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionFaultFaultMessage, UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionBaseFaultFaultMessage, UFIDAU9ISVMFGBOMIQueryBOMSvDoServiceLostExceptionFaultFaultMessage, UFIDAU9ISVMFGBOMIQueryBOMSvDoServiceExceptionDetailFaultFaultMessage;
}
