
package querybom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-01T18:34:02.055+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ExceptionBase", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")
public class UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionBaseFaultFaultMessage extends java.lang.Exception {
    
    private querybom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase;

    public UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionBaseFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionBaseFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionBaseFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionBaseFaultFaultMessage(String message, querybom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase) {
        super(message);
        this.exceptionBase = exceptionBase;
    }

    public UFIDAU9ISVMFGBOMIQueryBOMSvDoExceptionBaseFaultFaultMessage(String message, querybom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase, Throwable cause) {
        super(message, cause);
        this.exceptionBase = exceptionBase;
    }

    public querybom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase getFaultInfo() {
        return this.exceptionBase;
    }
}
