
package senditem.u9erp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-18T10:53:32.713+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceLostExceptionFaultFaultMessage extends java.lang.Exception {
    
    private senditem.u9erp.ServiceLostException serviceLostException;

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceLostExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceLostExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceLostExceptionFaultFaultMessage(String message, senditem.u9erp.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceLostExceptionFaultFaultMessage(String message, senditem.u9erp.ServiceLostException serviceLostException, Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public senditem.u9erp.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
