
package senditem.u9erp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-18T10:53:32.726+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ServiceExceptionDetail", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionDetailFaultFaultMessage extends java.lang.Exception {
    
    private senditem.u9erp.ServiceExceptionDetail serviceExceptionDetail;

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionDetailFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionDetailFaultFaultMessage(String message, senditem.u9erp.ServiceExceptionDetail serviceExceptionDetail) {
        super(message);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionDetailFaultFaultMessage(String message, senditem.u9erp.ServiceExceptionDetail serviceExceptionDetail, Throwable cause) {
        super(message, cause);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public senditem.u9erp.ServiceExceptionDetail getFaultInfo() {
        return this.serviceExceptionDetail;
    }
}
