package senditem.u9erp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-18T10:53:32.732+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.UFIDA.org", name = "UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV")
@XmlSeeAlso({ObjectFactory.class})
public interface UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSV {

    @Action(input = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV/Do", output = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV/DoResponse", fault = {@FaultAction(className = UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV/DoServiceExceptionFault"), @FaultAction(className = UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV/DoExceptionFault"), @FaultAction(className = UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceLostExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV/DoServiceLostExceptionFault"), @FaultAction(className = UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionBaseFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV/DoExceptionBaseFault"), @FaultAction(className = UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionDetailFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV/DoServiceExceptionDetailFault")})
    @RequestWrapper(localName = "Do", targetNamespace = "http://www.UFIDA.org", className = "senditem.u9erp.Do")
    @WebMethod(operationName = "Do", action = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.ItemSendSV.IFuwaItemSendSV/Do")
    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://www.UFIDA.org", className = "senditem.u9erp.DoResponse")
    public void _do(
        @WebParam(name = "context", targetNamespace = "http://www.UFIDA.org")
        java.lang.Object context,
        @WebParam(name = "itemInfo", targetNamespace = "http://www.UFIDA.org")
        senditem.u9erp.UFIDAU9CustFuwaPDMItemSendSVItemInfoDTOData itemInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "DoResult", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<java.lang.String> doResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "outMessages", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<ArrayOfMessageBase> outMessages
    ) throws UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionFaultFaultMessage, UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionFaultFaultMessage, UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceLostExceptionFaultFaultMessage, UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionBaseFaultFaultMessage, UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoServiceExceptionDetailFaultFaultMessage;
}
