
package senditem.u9erp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-18T10:53:32.706+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "Exception", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionFaultFaultMessage extends java.lang.Exception {
    
    private senditem.u9erp.Exception exception;

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionFaultFaultMessage(String message, senditem.u9erp.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public UFIDAU9CustFuwaPDMItemSendSVIFuwaItemSendSVDoExceptionFaultFaultMessage(String message, senditem.u9erp.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public senditem.u9erp.Exception getFaultInfo() {
        return this.exception;
    }
}
