package querybom.org.tempuri;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.teamcenter.clientx.WSconfig;

import querybom.org.ufida.UFIDAU9ISVMFGBOMIQueryBOMSv;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-01T18:34:02.099+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "QueryBOMSvStub", 
                  wsdlLocation = "http://192.168.2.70/U9/Services/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class QueryBOMSvStub extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "QueryBOMSvStub");
    public final static QName BasicHttpBindingUFIDAU9ISVMFGBOMIQueryBOMSv = new QName("http://tempuri.org/", "BasicHttpBinding_UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv");
    static {
        URL url = null;
        try {
            url = new URL(WSconfig.getUrl() + "U9/Services/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryBOMSvStub.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.2.70/U9/Services/UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv.svc?wsdl");
        } catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        WSDL_LOCATION = url;
    }

    public QueryBOMSvStub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryBOMSvStub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryBOMSvStub() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QueryBOMSvStub(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryBOMSvStub(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryBOMSvStub(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UFIDAU9ISVMFGBOMIQueryBOMSv
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv")
    public UFIDAU9ISVMFGBOMIQueryBOMSv getBasicHttpBindingUFIDAU9ISVMFGBOMIQueryBOMSv() {
        return super.getPort(BasicHttpBindingUFIDAU9ISVMFGBOMIQueryBOMSv, UFIDAU9ISVMFGBOMIQueryBOMSv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UFIDAU9ISVMFGBOMIQueryBOMSv
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.ISV.MFG.BOM.IQueryBOMSv")
    public UFIDAU9ISVMFGBOMIQueryBOMSv getBasicHttpBindingUFIDAU9ISVMFGBOMIQueryBOMSv(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingUFIDAU9ISVMFGBOMIQueryBOMSv, UFIDAU9ISVMFGBOMIQueryBOMSv.class, features);
    }

}
