
package syncbom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-28T09:57:49.506+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "Exception", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionFaultFaultMessage extends java.lang.Exception {
    
    private syncbom.org.datacontract.schemas._2004._07.system.Exception exception;

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.system.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.system.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public syncbom.org.datacontract.schemas._2004._07.system.Exception getFaultInfo() {
        return this.exception;
    }
}
