
package syncbom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-28T09:57:49.514+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ExceptionBase", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")
public class UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionBaseFaultFaultMessage extends java.lang.Exception {
    
    private syncbom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase;

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionBaseFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionBaseFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionBaseFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionBaseFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase) {
        super(message);
        this.exceptionBase = exceptionBase;
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoExceptionBaseFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase, Throwable cause) {
        super(message, cause);
        this.exceptionBase = exceptionBase;
    }

    public syncbom.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase getFaultInfo() {
        return this.exceptionBase;
    }
}
