
package syncbom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-28T09:57:49.523+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceLostExceptionFaultFaultMessage extends java.lang.Exception {
    
    private syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException;

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceLostExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceLostExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceLostExceptionFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceLostExceptionFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException, Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
