
package syncbom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-28T09:57:49.461+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ServiceException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionFaultFaultMessage extends java.lang.Exception {
    
    private syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException;

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
