
package syncbom.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-28T09:57:49.529+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ServiceExceptionDetail", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionDetailFaultFaultMessage extends java.lang.Exception {
    
    private syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail;

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionDetailFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionDetailFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail) {
        super(message);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public UFIDAU9CustFuwaPDMSyncBomCompontInfoSVISyncBomInfoSVDoServiceExceptionDetailFaultFaultMessage(String message, syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail, Throwable cause) {
        super(message, cause);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public syncbom.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail getFaultInfo() {
        return this.serviceExceptionDetail;
    }
}
