package queryitem.org.ufida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-25T08:49:08.216+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.UFIDA.org", name = "UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV")
@XmlSeeAlso({queryitem.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, queryitem.org.datacontract.schemas._2004._07.ufsoft.ObjectFactory.class, queryitem.org.datacontract.schemas._2004._07.ufsoft_ubf_util.ObjectFactory.class, queryitem.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, ObjectFactory.class, queryitem.org.datacontract.schemas._2004._07.ufsoft_ubf.ObjectFactory.class, queryitem.exceptions.ubf.ufsoft.ObjectFactory.class, queryitem.org.datacontract.schemas._2004._07.system.ObjectFactory.class})
public interface UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV {

    @WebMethod(operationName = "Do", action = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV/Do")
    @Action(input = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV/Do", output = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV/DoResponse", fault = {@FaultAction(className = UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV/DoServiceExceptionFault"), @FaultAction(className = UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoExceptionBaseFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV/DoExceptionBaseFault"), @FaultAction(className = UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceLostExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV/DoServiceLostExceptionFault"), @FaultAction(className = UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV/DoExceptionFault"), @FaultAction(className = UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceExceptionDetailFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV/DoServiceExceptionDetailFault")})
    @RequestWrapper(localName = "Do", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.Do")
    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.DoResponse")
    public void _do(
        @WebParam(name = "context", targetNamespace = "http://www.UFIDA.org")
        java.lang.Object context,
        @WebParam(name = "org", targetNamespace = "http://www.UFIDA.org")
        java.lang.Long org,
        @WebParam(name = "sPECS", targetNamespace = "http://www.UFIDA.org")
        java.lang.String sPECS,
        @WebParam(name = "queryType", targetNamespace = "http://www.UFIDA.org")
        java.lang.Integer queryType,
        @WebParam(mode = WebParam.Mode.OUT, name = "DoResult", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<queryitem.com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring> doResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "outMessages", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<queryitem.exceptions.ubf.ufsoft.ArrayOfMessageBase> outMessages
    ) throws UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceExceptionFaultFaultMessage, UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoExceptionBaseFaultFaultMessage, UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceLostExceptionFaultFaultMessage, UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoExceptionFaultFaultMessage, UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceExceptionDetailFaultFaultMessage;
}
