
package queryitem.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-25T08:49:08.195+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceLostExceptionFaultFaultMessage extends java.lang.Exception {
    
    private queryitem.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException;

    public UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceLostExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceLostExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceLostExceptionFaultFaultMessage(String message, queryitem.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSVDoServiceLostExceptionFaultFaultMessage(String message, queryitem.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException, Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public queryitem.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
