package alteritem.org.tempuri;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.teamcenter.clientx.WSconfig;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-21T16:11:44.130+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ModifyItemForSDByCustSV", 
                  wsdlLocation = "http://192.168.2.70/BarCodeWeb/ModifyItemForSDByCustSV.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ModifyItemForSDByCustSV extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ModifyItemForSDByCustSV");
    public final static QName ModifyItemForSDByCustSVSoap = new QName("http://tempuri.org/", "ModifyItemForSDByCustSVSoap");
    public final static QName ModifyItemForSDByCustSVSoap12 = new QName("http://tempuri.org/", "ModifyItemForSDByCustSVSoap12");
    static {
        URL url = null;
        try {
            url = new URL(WSconfig.getUrl() + "BarCodeWeb/ModifyItemForSDByCustSV.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ModifyItemForSDByCustSV.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.2.70/BarCodeWeb/ModifyItemForSDByCustSV.asmx?wsdl");
        } catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        WSDL_LOCATION = url;
    }

    public ModifyItemForSDByCustSV(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ModifyItemForSDByCustSV(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModifyItemForSDByCustSV() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ModifyItemForSDByCustSV(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ModifyItemForSDByCustSV(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ModifyItemForSDByCustSV(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ModifyItemForSDByCustSVSoap
     */
    @WebEndpoint(name = "ModifyItemForSDByCustSVSoap")
    public ModifyItemForSDByCustSVSoap getModifyItemForSDByCustSVSoap() {
        return super.getPort(ModifyItemForSDByCustSVSoap, ModifyItemForSDByCustSVSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifyItemForSDByCustSVSoap
     */
    @WebEndpoint(name = "ModifyItemForSDByCustSVSoap")
    public ModifyItemForSDByCustSVSoap getModifyItemForSDByCustSVSoap(WebServiceFeature... features) {
        return super.getPort(ModifyItemForSDByCustSVSoap, ModifyItemForSDByCustSVSoap.class, features);
    }


    /**
     *
     * @return
     *     returns ModifyItemForSDByCustSVSoap
     */
    @WebEndpoint(name = "ModifyItemForSDByCustSVSoap12")
    public ModifyItemForSDByCustSVSoap getModifyItemForSDByCustSVSoap12() {
        return super.getPort(ModifyItemForSDByCustSVSoap12, ModifyItemForSDByCustSVSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModifyItemForSDByCustSVSoap
     */
    @WebEndpoint(name = "ModifyItemForSDByCustSVSoap12")
    public ModifyItemForSDByCustSVSoap getModifyItemForSDByCustSVSoap12(WebServiceFeature... features) {
        return super.getPort(ModifyItemForSDByCustSVSoap12, ModifyItemForSDByCustSVSoap.class, features);
    }

}
