
package querymaterial.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-01T18:33:50.347+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "Exception", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionFaultFaultMessage extends java.lang.Exception {
    
    private querymaterial.org.datacontract.schemas._2004._07.system.Exception exception;

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionFaultFaultMessage(String message, querymaterial.org.datacontract.schemas._2004._07.system.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionFaultFaultMessage(String message, querymaterial.org.datacontract.schemas._2004._07.system.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public querymaterial.org.datacontract.schemas._2004._07.system.Exception getFaultInfo() {
        return this.exception;
    }
}
