
package querymaterial.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-01T18:33:50.358+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ExceptionBase", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")
public class UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionBaseFaultFaultMessage extends java.lang.Exception {
    
    private querymaterial.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase;

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionBaseFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionBaseFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionBaseFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionBaseFaultFaultMessage(String message, querymaterial.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase) {
        super(message);
        this.exceptionBase = exceptionBase;
    }

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoExceptionBaseFaultFaultMessage(String message, querymaterial.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase, Throwable cause) {
        super(message, cause);
        this.exceptionBase = exceptionBase;
    }

    public querymaterial.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase getFaultInfo() {
        return this.exceptionBase;
    }
}
