
package querymaterial.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-01T18:33:50.377+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "ServiceExceptionDetail", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoServiceExceptionDetailFaultFaultMessage extends java.lang.Exception {
    
    private querymaterial.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail;

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoServiceExceptionDetailFaultFaultMessage() {
        super();
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoServiceExceptionDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoServiceExceptionDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoServiceExceptionDetailFaultFaultMessage(String message, querymaterial.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail) {
        super(message);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public UFIDAU9ISVItemIBatchQueryItemByDTOSRVDoServiceExceptionDetailFaultFaultMessage(String message, querymaterial.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail, Throwable cause) {
        super(message, cause);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public querymaterial.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail getFaultInfo() {
        return this.serviceExceptionDetail;
    }
}
