package querymaterial2.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-09T09:02:25.558+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "QueryItemByCustSVSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryItemByCustSVSoap {

    @WebResult(name = "DoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Do", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Do")
    @WebMethod(operationName = "Do", action = "http://tempuri.org/Do")
    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DoResponse")
    public java.lang.String _do(
        @WebParam(name = "itemCode", targetNamespace = "http://tempuri.org/")
        java.lang.String itemCode,
        @WebParam(name = "orgID", targetNamespace = "http://tempuri.org/")
        java.lang.String orgID,
        @WebParam(name = "userID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(name = "userCode", targetNamespace = "http://tempuri.org/")
        java.lang.String userCode,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName
    );
}
