package querymaterial2.org.tempuri;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.teamcenter.clientx.WSconfig;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-09T09:02:25.645+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "QueryItemByCustSV", 
                  wsdlLocation = "http://192.168.2.71/BarCodeWeb/QueryItemByCustSV.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class QueryItemByCustSV extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "QueryItemByCustSV");
    public final static QName QueryItemByCustSVSoap12 = new QName("http://tempuri.org/", "QueryItemByCustSVSoap12");
    public final static QName QueryItemByCustSVSoap = new QName("http://tempuri.org/", "QueryItemByCustSVSoap");
    static {
        URL url = null;
        try {
            url = new URL(WSconfig.getUrl() + "BarCodeWeb/QueryItemByCustSV.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryItemByCustSV.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.2.71/BarCodeWeb/QueryItemByCustSV.asmx?wsdl");
        } catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        WSDL_LOCATION = url;
    }

    public QueryItemByCustSV(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryItemByCustSV(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryItemByCustSV() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QueryItemByCustSV(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryItemByCustSV(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryItemByCustSV(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QueryItemByCustSVSoap
     */
    @WebEndpoint(name = "QueryItemByCustSVSoap12")
    public QueryItemByCustSVSoap getQueryItemByCustSVSoap12() {
        return super.getPort(QueryItemByCustSVSoap12, QueryItemByCustSVSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryItemByCustSVSoap
     */
    @WebEndpoint(name = "QueryItemByCustSVSoap12")
    public QueryItemByCustSVSoap getQueryItemByCustSVSoap12(WebServiceFeature... features) {
        return super.getPort(QueryItemByCustSVSoap12, QueryItemByCustSVSoap.class, features);
    }


    /**
     *
     * @return
     *     returns QueryItemByCustSVSoap
     */
    @WebEndpoint(name = "QueryItemByCustSVSoap")
    public QueryItemByCustSVSoap getQueryItemByCustSVSoap() {
        return super.getPort(QueryItemByCustSVSoap, QueryItemByCustSVSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryItemByCustSVSoap
     */
    @WebEndpoint(name = "QueryItemByCustSVSoap")
    public QueryItemByCustSVSoap getQueryItemByCustSVSoap(WebServiceFeature... features) {
        return super.getPort(QueryItemByCustSVSoap, QueryItemByCustSVSoap.class, features);
    }

}
