package queryitem.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.teamcenter.clientx.WSconfig;

import queryitem.org.ufida.UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-25T08:49:08.237+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "QueryItemCodeFromSPECSSVStub", 
                  wsdlLocation = "http://192.168.2.70/U9/Services/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV.svc?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class QueryItemCodeFromSPECSSVStub extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "QueryItemCodeFromSPECSSVStub");
    public final static QName BasicHttpBindingUFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV = new QName("http://tempuri.org/", "BasicHttpBinding_UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV");
    static {
        URL url = null;
        try {
            url = new URL(WSconfig.getUrl()+"U9/Services/UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV.svc?wsdl");
        } catch (Exception e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }
    public QueryItemCodeFromSPECSSVStub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryItemCodeFromSPECSSVStub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryItemCodeFromSPECSSVStub() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryItemCodeFromSPECSSVStub(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryItemCodeFromSPECSSVStub(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryItemCodeFromSPECSSVStub(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV")
    public UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV getBasicHttpBindingUFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV() {
        return super.getPort(BasicHttpBindingUFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV, UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.Cust.Fuwa.PDM.QueryItemCodeFromSPECSSV.IQueryItemCodeFromSPECSSV")
    public UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV getBasicHttpBindingUFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingUFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV, UFIDAU9CustFuwaPDMQueryItemCodeFromSPECSSVIQueryItemCodeFromSPECSSV.class, features);
    }

}
